#!/usr/bin/env bash

executor="doas"

if [ $# -eq 0 ]
then
	dapt -v
	dapt -h
	exit 1
fi

command="$1"
shift

case "$command" in
	-h|--help)
		echo "Usage: dapt [command] [arguments]"
		echo "Commands:"
		echo "  ud   update"
		echo "  ug   upgrade"
		echo "  uu   update && upgrade"
		echo "  pg   autopurge && clean"
		echo "  up   update && upgrade && autopurge && clean"
		echo "  in   install"
		echo "  se   search"
		echo "  sn   search --names-only"
		echo "  sh   show"
		echo "  ls   list"
		echo "  li   list --installed"
		echo "Use with caution: all operations are performed unsandboxed as root."
		;;
	-v|--version)
		echo "dapt version 1.3"
		;;
	ud)
		$executor apt update
		;;
	ug)
		$executor apt upgrade "$@"
		;;
	uu)
		$executor apt update && $executor apt upgrade "$@"
		;;
	pg)
		$executor apt autopurge "$@" && $executor apt clean
		;;
	up)
		$executor apt update && $executor apt upgrade && $executor apt autopurge && $executor apt clean
		;;
	in)
		$executor apt install "$@"
		;;
	se)
		$executor apt search "$@"
		;;
	sn)
		$executor apt search --names-only "$@"
		;;
	sh)
		$executor apt show "$@"
		;;
	ls)
		$executor apt list "$@"
		;;
	li)
		$executor apt list --installed "$@"
		;;
	*)
		echo "Command not found: \"$command\""
		exit 1
		;;
esac

exit 0
